# Generated by Django 6.0.1 on 2026-05-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_sessions', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Button/Link Click'), ('form', 'Form Submission'), ('custom', 'Custom Event')], max_length=20)),
                ('element_id', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pages.pageview')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics_sessions.session')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
